# config.py
MARGIN = 0.1

TICKERS = [
    "AAPL", "MSFT", "AMZN", "GOOGL", "GOOG", "FB", "TSLA", "BRK.B", "NVDA", "JPM",
    "JNJ", "V", "UNH", "PG", "HD", "BAC", "DIS", "MA", "PYPL", "VZ",
    "ADBE", "NFLX", "INTC", "CMCSA", "PFE", "KO", "PEP", "T", "XOM", "CSCO",
    "ABT", "MRK", "NKE", "CRM", "LLY", "TMO", "AVGO", "WMT", "ACN", "COST",
    "DHR", "NEE", "MCD", "MDT", "WFC", "HON", "UNP", "LIN", "TXN", "AMGN",
    "MS", "PM", "BMY", "QCOM", "SCHW", "C", "IBM", "ORCL", "BA", "UPS",
    "GS", "SBUX", "RTX", "BLK", "CAT", "CVX", "LOW", "SPGI", "AMT", "INTU",
    "MMM", "ISRG", "MDLZ", "GE", "AXP", "PLD", "ADP", "CB", "MO", "ZTS",
    "CCI", "SYK", "TGT", "DE", "BDX", "SCHW", "MMC", "DUK", "CI", "PGR",
    "SO", "USB", "TFC", "EL", "ADI", "ITW", "HUM", "AMAT", "NOC", "MU",
    "BKNG", "GM", "GILD", "FIS", "LMT", "TJX", "NSC", "FISV", "CSX", "HCA",
    "PNC", "ICE", "COP", "MET", "EW", "VRTX", "TRV", "ETN", "CME", "PSA",
    "MCO", "GD", "MPC", "ADSK", "MAR", "KMB", "AON", "FDX", "ADP", "ECL",
    "NOC", "APH", "JCI", "DG", "COF", "SPG", "KLAC", "MNST", "AZO", "APTV",
    "FTNT", "EOG", "ROST", "BAX", "RMD", "CTAS", "KMI", "O", "WMB", "IQV",
    "MCK", "BSX", "D", "CDNS", "AEP", "SHW", "TT", "EA", "PEG", "RSG",
    "STZ", "ATO", "EXC", "CTSH", "PPG", "WY", "DOV", "PSX", "ALL", "WEC",
    "SRE", "CMG", "PCAR", "HSY", "CARR", "ILMN", "AME", "AVB", "SLB", "BKR",
    "ZBH", "MSCI", "PH", "HPQ", "HES", "DTE", "ES", "DLR", "DVN", "OKE",
    "FAST", "AFL", "VFC", "CERN", "MSI", "DHI", "EBAY", "ED", "MTB", "SYY",
    "WAT", "AIG", "RCL", "FMC", "MKC", "LYB", "FTV", "EMN", "EMR", "CMS",
    "CSL", "ATO", "KEYS", "BBY", "HRL", "FLT", "TSCO", "GWW", "XRAY", "LUV",
    "FFIV", "TDY", "XEL", "REGN", "WDC", "TROW", "WYNN", "HIG", "J", "DISH",
    "CAG", "UAL", "A", "AKAM", "PWR", "COO", "MAS", "NRG", "BBY", "ETR",
    "ANET", "PAYC", "DD", "CTXS", "DRE", "SEE", "ZBRA", "ESS", "ODFL", "DPZ",
    "SBAC", "AEE", "ABC", "LNT", "NTAP", "K", "MKTX", "CINF", "MRO", "IR",
    "VRSK", "NDAQ", "HST", "ROK", "ALLE", "KMX", "LH", "EXR", "ANSS", "LDOS",
    "TDG", "TECH", "NRG", "NTAP", "CNP", "HII", "AAP", "WRB", "ALGN", "CBOE",
    "HOLX", "AES", "LHX", "CPT", "CCL", "CMS", "MAS", "MTD", "NLOK", "EXPD",
    "HAS", "GPC", "IP", "OKE", "VMC", "IPG", "PKI", "ETSY", "WST", "AVY",
    "HWM", "XRAY", "CFG", "BEN", "CDW", "NTRS", "LUMN", "PXD", "POOL", "PEAK",
    "RF", "UDR", "CMA", "DRI", "FRT", "AES", "VTRS", "WHR", "PBCT", "JPM",
    "FTI", "TAP", "WAB", "CLX", "FE", "AES", "CMS", "AWK", "PPL", "PNW",
    "ESS", "FITB", "BF.B", "OKE", "DLR", "ATO", "ESS", "CMS", "VTRS", "TAP",
    "EXPE", "ABMD", "ARE", "MAA", "UDR", "FMC", "BRX", "MPWR", "WYNN", "FRT",
    "PPL", "ATO", "CMS", "VTRS", "CPT", "UDR", "HRB", "ZION", "BEN", "WY",
    "HBAN", "PFG", "MTB", "CFG", "GPC", "EVRG", "SLG", "SBAC", "STT", "FRC"
]

